Vagrant.configure("2") do |config|
  config.vm.box_version = "20211026.0.0"
  config.vm.box = "ubuntu/focal64"
  
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.linked_clone = true
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "main" do |server|
    server.vm.provider :virtualbox do |serverv|
      serverv.memory = 2048
    end
    server.vm.hostname = "internal-server.test"
    server.vm.network :private_network, ip: "192.168.56.101"
  end

  config.vm.define "peer1" do |peer|
    peer.vm.hostname = "internal-peer1.test"
    peer.vm.network :private_network, ip: "192.168.56.102"
  end

  config.vm.define "peer2" do |peer|
    peer.vm.hostname = "internal-peer2.test"
    peer.vm.network :private_network, ip: "192.168.56.103"
  end
end
